spring:
  application:
    name: activityService
  data:
    mongodb:
      uri: mongodb://localhost:27017
      database: fitnessactivity

server:
  port: 8082

eureka:
  client:
    serviceUrl:
      defaultZone: http://localhost:8761/eureka/
