server:
  port: 8080
spring:
  application:
    name: api-gateway
  security:
    oauth2:
      resourceserver:
        jwt:
          jwk-set-uri: http://localhost:8181/realms/fitness-oauth2/protocol/openid-connect/certs
  cloud:
    gateway:
      routes:
        - id: user-service
          uri: http://127.0.0.1:8081
          predicates:
            - Path=/api/users/**
        - id: activity-service
          uri: http://127.0.0.1:8082
          predicates:
            - Path=/api/activities/**
        - id: ai-service
          uri: http://127.0.0.1:8083
          predicates:
            - Path=/api/recommendations/**


  eureka:
    client:
      service-url:
        defaultZone: http://localhost:8761/eureka/